### ISSUE TITLE
无法获取正确的IP

### ISSUE THREAD

**Issue by VwEl** [MoeGuoH/Xunlei-XlNetAcc-Keeper#2]
会获取到一个47.103.70.19的IP地址

**Comment by MoeGuoH** [comment]
这个是加速通道的IP地址,和你的真实地址无关.

**Comment by VwEl** [comment]
> 
> 
> 这个是加速通道的IP地址,和你的真实地址无关.

然后输出信息是[Info]:already speedup in another network

**Comment by MoeGuoH** [comment]
> > 这个是加速通道的IP地址,和你的真实地址无关.
> 
> 然后输出信息是[Info]:already speedup in another network

那请确保自己在网页版快鸟能加速,若不能,请和快鸟官方客户反馈.
